twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        stripe_public_key: '%env(default::STRIPE_PUBLIC_KEY)%'

when@test:
    twig:
        strict_variables: true
